
/*
 * This file is generated by a script, do not edit.
 *
 * This documentation string was generated from
 * a C comment block within a mex program
 * by `doc2docstring.py' on Sun Oct 25 23:33:12 2009.
 */
 
static const char docstring[] =
	"hmi_segment	driver for HMI segmentation\n"
	"\n"
	" y=hmi_segment(xm,xp,del,ctr,rho,mode,mod1,...)\n"
	" * This is implemented as a MEX file.\n"
	"\n"
	" Inputs:\n"
	"   real xm(m,n)\n"
	"   real xp(m,n)\n"
	"   int iter[1] or [2] = [0 0.05];\n"
	"   real T[0] or [1] or [2] or [3] or [4] = [1 1 0.8 0];\n"
	"   real beta[1] or [K,K];\n"
	"   real alpha[K] or [0] = [];\n"
	"   real ctr(3) or ctr(4) or ctr(5);\n"
	"   real rho;\n"
	"   string mode\n"
	"   real m1(l,k1)\n"
	"   ...\n"
	"   real mR(l,kR)\n"
	"\n"
	" Outputs:\n"
	"   int y(m,n)\n"
	"   real post\n"
	"\n"
	" See Also:  makemrfdiscwts, mrf_segment_wts4, mixNprobNd\n"
	"\n"
	" turmon oct 2009\n"
	"\n"
	"";

/* End of generated file */

