
/*
 * This file is generated by a script, do not edit.
 *
 * This documentation string was generated from
 * a C comment block within a mex program
 * by `doc2docstring.py' on Thu Jun 23 18:26:52 2011.
 */
 
static const char docstring[] =
	"loadfitsa: load array from file in FITS format\n"
	"\n"
	" [image, error, params] = loadfitsa(file, block, type)\n"
	" * File is the name of the fits file to be read, which is an\n"
	" arbitrary-dimensional fits file.  It is loaded into Matlab in\n"
	" the \"natural\" ordering -- the native fits ordering, Fortran\n"
	" progession of coordinates.  The standard fitsio naming shortcuts\n"
	" are accepted, including 'file.fits[1]' for the first image\n"
	" extension, useful for loading compressed images in bintables.\n"
	" * If the primary HDU (indexed 0 in the shortcut above) is empty,\n"
	" i.e. has NAXIS = 0, then we try each following HDU until one is\n"
	" non-empty to look for valid data.\n"
	" * Block is the blocking factor; only elements 1, block+1, ...\n"
	" are loaded (in every dimension).\n"
	" * type is the destination Matlab type, e.g. 'double' or 'int32'.\n"
	" When using the integer types, be aware that the input FITS file\n"
	" must fit within the range of the given type, or there will be\n"
	" an error.\n"
	" * The resulting array is returned; this is 0x0 if an error occurs.\n"
	" * Error is 1 if there was an error, 0 otherwise.  An error\n"
	" synopsis is printed if error = 1.\n"
	" * To allow robust scripting, if error is requested, a matlab\n"
	" error is not raised even if a file-related error occurs.  The\n"
	" error flag is set, and a message is printed, but mexErrMsgTxt is\n"
	" not called.  (Exception: if the arguments are malformed, as\n"
	" opposed to a file-reading problem, a mex error *is* raised.)\n"
	" * params, encodes the following parameters: bitpix, bscale, bzero, blank.\n"
	" It can be useful to have access to the way the FITS file was encoded.\n"
	" * loadfitsa and savefitsa are inverse functions.\n"
	"\n"
	" Inputs:\n"
	"   string filename\n"
	"   opt int block = 1\n"
	"   opt string type = 'double'\n"
	"\n"
	" Outputs:\n"
	"   real image(...)\n"
	"   int error\n"
	"   real params(4)\n"
	"\n"
	" See Also: savefitsa\n"
	"\n"
	" implemented as a MEX file.\n"
	" rewritten by turmon aug 2002\n"
	" touched up for 64-bit, better error reporting, arb. class out, 4/2010.\n"
	"\n"
	"";

/* End of generated file */

