SUBROUTINE FREE_MEMORY
  !
  ! J M Borrero
  ! Dec 16, 2009
  ! HAO-NCAR for HMI-Stanford
  !
  USE FILT_PARAM
  USE CONS_PARAM
  USE LINE_PARAM
  USE INV_PARAM
  IMPLICIT NONE
  !
  DEALLOCATE(FILTER, TUNEPOS, FREELOC)
  DEALLOCATE(WAVE)
  !
END SUBROUTINE FREE_MEMORY
!CVSVERSIONINFO "$Id: free_memory.f90,v 1.4 2012/04/09 22:21:05 keiji Exp $"
