SUBROUTINE INV_INIT (NUM_ITERATIONS, SVD_TOLERANCE, CHI2_STOP, POLARIZATION_THRESHOLD, &
     INTENSITY_THRESHOLD)
  !
  ! J M Borrero
  ! Dec 14, 2009
  ! HAO-NCAR for HMI-Stanford
  !
  USE CONS_PARAM
  USE INV_PARAM
  IMPLICIT NONE
  REAL(DP), INTENT(IN), OPTIONAL :: SVD_TOLERANCE, CHI2_STOP, POLARIZATION_THRESHOLD
  REAL(DP), INTENT(IN), OPTIONAL :: INTENSITY_THRESHOLD
  INTEGER,  INTENT(IN)           :: NUM_ITERATIONS
  !
  ITER=NUM_ITERATIONS
  SVDTOL = SVD_TOLERANCE
  GOODFIT = CHI2_STOP
  TREPOL =  POLARIZATION_THRESHOLD
  TREIC = INTENSITY_THRESHOLD
  !
END SUBROUTINE INV_INIT
!CVSVERSIONINFO "$Id: inv_init.f90,v 1.5 2012/04/10 22:16:54 keiji Exp $"
