SUBROUTINE LINE_INIT (LAMBDA_0, LAMBDA_B, NOISE_LEVEL)
  !
  ! J M Borrero
  ! Dec 14, 2009
  ! HAO-NCAR for HMI-Stanford
  !
  USE CONS_PARAM
  USE LINE_PARAM
  IMPLICIT NONE
  REAL(DP), INTENT(IN)      :: LAMBDA_0, LAMBDA_B, NOISE_LEVEL
  LANDA0 = LAMBDA_0
  SHIFT = LAMBDA_B
  NOISE = NOISE_LEVEL
  !
END SUBROUTINE LINE_INIT
!CVSVERSIONINFO "$Id: line_init.f90,v 1.2 2011/05/31 22:24:54 keiji Exp $"
