SUBROUTINE SVD_INIT
  USE SVD_PARAM
  USE INV_PARAM
  IMPLICIT NONE
  INTEGER                    :: I, J
  NUMFREE_PARAM = 0
  DO I=1,10
     IF (FREE(I).EQ..TRUE.) NUMFREE_PARAM=NUMFREE_PARAM+1
  ENDDO
  ALLOCATE (FREELOC(NUMFREE_PARAM))
  J=1
  DO I=1,10
     IF (FREE(I).EQ..TRUE.) THEN
        FREELOC(J)=I
        J=J+1
     ENDIF
  ENDDO
  ALLOCATE(HESS(NUMFREE_PARAM,NUMFREE_PARAM),DIVC(NUMFREE_PARAM))
  !
END SUBROUTINE SVD_INIT
  
!CVSVERSIONINFO "$Id: svd_init.f90,v 1.2 2011/05/31 22:25:19 keiji Exp $"
