SUBROUTINE WAVE_INIT (LAMBDA_MIN, DELTA_LAMBDA, NUM_LAMBDA)
  !
  ! J M Borrero
  ! Dec 14, 2009
  ! HAO-NCAR for HMI-Stanford
  USE CONS_PARAM
  USE LINE_PARAM
  IMPLICIT NONE
  REAL(DP), INTENT(IN) :: LAMBDA_MIN, DELTA_LAMBDA
  INTEGER,  INTENT(IN) :: NUM_LAMBDA
  INTEGER              :: I
  !
  NUMW=NUM_LAMBDA
  STEPW=DELTA_LAMBDA
  WRITE(*,*) DELTA_LAMBDA
  ALLOCATE (WAVE(NUMW))
  WRITE(*,*) NUMW 
  !
  DO I=1,NUMW
     WAVE(I)=LAMBDA_MIN+DBLE(I-1)*STEPW
  ENDDO
  !
END SUBROUTINE WAVE_INIT
!CVSVERSIONINFO "$Id: wave_init.f90,v 1.2 2011/05/31 22:25:52 keiji Exp $"
