# MUST FIRST MAKE UTIL LIBS, THEN MEX2C LIBS. MAKE A DEPENDENCY OF MEX2C ON UTIL. It uses mexhead.h generated by UTIL.
# Standard things                                                                                             
sp              := $(sp).x
dirstack_$(sp)  := $(d)
d               := $(dir)

# OUTDIR is the root directory that contains all make-generated binary files
# PDIR is the sub-directory of OUTDIR that is the parent 
OUTDIR		:= $(WORKINGDIR)/_$(MACH)
PSDIR		:= $(d)

# Util libraries
UTILSDIR	:= mex/src/util
CSDIRUTIL	:= $(PSDIR)/$(UTILSDIR)
LIBEXRNG	:= $(OUTDIR)/$(PSDIR)/$(UTILSDIR)/libmexrng.a
LIBMEXTOOLS	:= $(OUTDIR)/$(PSDIR)/$(UTILSDIR)/libmextoolsMW.a
METAHEADER	:= $(OUTDIR)/$(PSDIR)/$(UTILSDIR)/mexhead.h

SUTIL_$(d)		:= $(notdir $(LIBEXRNG) $(LIBMEXTOOLS) $(METAHEADER))
S1UTIL_$(d)		:= $(addprefix $(PSDIR)/$(UTILSDIR)/, $(SUTIL_$(d)))

$(LIBEXRNG) $(LIBMEXTOOLS) $(METAHEADER):
	$(MAKE) -C $(WORKINGDIR)/$(PSDIR)/$(UTILSDIR) OUTDIR=$(OUTDIR) CSDIR=$(CSDIRUTIL) $@

.PHONY:	$(SUTIL_$(d))
$(SUTIL_$(d)):	%:	$(OUTDIR)/$(PSDIR)/$(UTILSDIR)/%

.PHONY:	$(S1UTIL_$(d))
$(S1UTIL_$(d)):	%:	$(OUTDIR)/%


# mex2c libraries

# Don't even try to re-use variables in the 'recipes' - make will have problems. 
# I tried re-using CSDIR, and apparently that will cause the value of $(CSDIR) on 
# line 23 to change, even though line 23 comes before line 36. 
MEX2CSDIR	:= mex/src/mex2c
CSDIRMEX2C	:= $(PSDIR)/$(MEX2CSDIR)
LIBMEX2C	:= $(OUTDIR)/$(PSDIR)/$(MEX2CSDIR)/libmex2c_lib.a
LIBMEX2MATL	:= $(OUTDIR)/$(PSDIR)/$(MEX2CSDIR)/libmex2matl.a

SMEX2C_$(d)		:= $(notdir $(LIBMEX2C) $(LIBMEX2MATL))
S1MEX2C_$(d)		:= $(addprefix $(PSDIR)/$(MEX2CSDIR)/, $(SMEX2C_$(d)))

# Don't rely upon $(PWD) to tell you make's current working directory. It lies! Instead of trying 
# to come up with a path relative to where you think make is, just avoid relative paths altogether.
$(LIBMEX2C) $(LIBMEX2MATL):
	$(MAKE) -C $(WORKINGDIR)/$(PSDIR)/$(MEX2CSDIR) OUTDIR=$(OUTDIR) CSDIR=$(CSDIRMEX2C) $@
#        $(MAKE) -C mfile-mex OUTDIR=$(CURDIR)/$(d) $@

.PHONY:	$(SMEX2C_$(d))
$(SMEX2C_$(d)):	%:	$(OUTDIR)/$(PSDIR)/$(MEX2CSDIR)/%

.PHONY:	$(S1MEX2C_$(d))
$(S1MEX2C_$(d)):	%:	$(OUTDIR)/%


TGT_LIB         := $(TGT_LIB) $(LIBMEX2MATL) $(LIBMEX2C) $(LIBEXRNG) $(LIBMEXTOOLS) $(METAHEADER)

# Standard things                                                                
-include        $(DEP_$(d))

d               := $(dirstack_$(sp))
sp              := $(basename $(sp))
