
/*
 * This file is generated by a script, do not edit.
 *
 * This documentation string was generated from
 * a C comment block within a mex program
 * by `doc2docstring.py' on Thu Jun 23 18:26:51 2011.
 */
 
static const char docstring[] =
	"assignment: solve linear sum assignment problem\n"
	"\n"
	" [pi1,pi2,s]=assignment(rho)\n"
	" * Solves linear-sum assignment problem with *integer* costs\n"
	" given in rho.\n"
	" * Outputs the maximizing permutation pi1, its inverse pi2,\n"
	" and the maximizing cost s.\n"
	"\n"
	" Inputs:\n"
	"  int rho(m,n)\n"
	"\n"
	" Outputs:\n"
	"  int pi1(m)\n"
	"  int pi2(n)\n"
	"  int s\n"
	"\n"
	" See Also:\n"
	"\n"
	" turmon apr 2008\n"
	" original authors: Benjamin J. Bornstein, Becky Castano\n"
	"\n"
	"";

/* End of generated file */

